### ISSUE TITLE
feed/rss - PHP Fatal error:  Uncaught Error: Class "SimpleXMLElement" not found

### ISSUE THREAD

**Issue by rb2** [danpros/htmly#600]
HTMLy 2.8.2, PHP 8.1.2, Apache2

RSS feed failed with server error 500 and next entry in apache log:

```
PHP Fatal error:  Uncaught Error: Class "SimpleXMLElement" not found
in .../system/vendor/suin/php-rss-writer/src/Suin/RSSWriter/SimpleXMLElement.php:9

Stack trace:
#0 .../system/vendor/composer/ClassLoader.php(444): include()
#1 .../system/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile()
#2 .../system/vendor/suin/php-rss-writer/src/Suin/RSSWriter/Feed.php(33): Composer\\Autoload\\ClassLoader->loadClass()
#3 .../system/vendor/suin/php-rss-writer/src/Suin/RSSWriter/Feed.php(53): Suin\\RSSWriter\\Feed->render()
#4 .../system/includes/functions.php(2369): Suin\\RSSWriter\\Feed->__toString()
#5 .../system/htmly.php(2204): generate_rss()
#6 .../system/includes/dispatch.php(506): {closure}()
#7 .../system/includes/dispatch.php(570): route()
#8 .../system/htmly.php(3597): dispatch()
#9 .../index.php(5): require('...')
#10 {main}
  thrown in .../system/vendor/suin/php-rss-writer/src/Suin/RSSWriter/SimpleXMLElement.php on line 9
```

**Comment by JPLeRouzic** [comment]
Please look at this answer and tell us if the php-xml library is installed on your server.
https://stackoverflow.com/questions/46610501/class-simplexmlelement-not-found

**Comment by rb2** [comment]
Thank you, solved!
`php-xml` was not installed on new server.
